
set(PICO_PLATFORM rp2350)
set(PICO_RP2350_A2_SUPPORTED 1)
set(CONFIG_USB_DEVICE 1)
set(CONFIG_SD_STORAGE 1)
set(CONFIG_FLASH_FAT_STORAGE 0)
set(CONFIG_FLASH_LFS_STORAGE 0)
set(CONFIG_JLP 1)
set(CONFIG_ECS_AUDIO 0)
set(PICO_FLASH_SIZE_BYTES 4194304)
set(PICO_FLASH_SPI_CLKDIV 2)

if(CMAKE_BUILD_TYPE STREQUAL "Release")
   set(CONFIG_USB_DEVICE 0)
   set(MAX_ROM_SIZE 1024*218)    # ~448 kb
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
   set(CONFIG_USB_DEVICE 1)
   set(MAX_ROM_SIZE 1024*205)    # ~410 kb
endif()
