
set(PICO_PLATFORM rp2040)
set(CONFIG_USB_DEVICE 1)
set(CONFIG_SD_STORAGE 0)
set(CONFIG_FLASH_FAT_STORAGE 1)
set(CONFIG_FLASH_LFS_STORAGE 0)
set(CONFIG_JLP 0)
set(CONFIG_ECS_AUDIO 0)
set(PICO_FLASH_SIZE_BYTES 16777216)
set(PICO_FLASH_SPI_CLKDIV 2)

if(CMAKE_BUILD_TYPE STREQUAL "Release")
   set(MAX_ROM_SIZE 1024*74)  # ~144 kb 
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
   set(MAX_ROM_SIZE 1024*64)  # ~128 kb
endif()

