
set(PICO_PLATFORM rp2350)
set(PICO_RP2350_A2_SUPPORTED 1)
set(CONFIG_USB_DEVICE 1)
set(CONFIG_SD_STORAGE 1)
set(CONFIG_FLASH_FAT_STORAGE 0)
# testing 
set(CONFIG_FLASH_LFS_STORAGE 1)
#
set(CONFIG_JLP 1)
set(PICO_FLASH_SIZE_BYTES 4194304)
set(PICO_FLASH_SPI_CLKDIV 2)

if(CMAKE_BUILD_TYPE STREQUAL "Release")
   set(CONFIG_USB_DEVICE 0)
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
   set(CONFIG_USB_DEVICE 1)
endif()
